services:
  mongodb:
    image: mongo:7
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: YouthDb

  mongo-express:
    image: mongo-express
    container_name: mongo-ui
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
      ME_CONFIG_BASICAUTH_USERNAME: admin@youth.com
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  backend:
    build: ./backend
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID:-608842325431-buobeotqh04mjffo7irppi27guqadkvi.apps.googleusercontent.com}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - backend
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL

volumes:
  mongo_data:
